### ISSUE TITLE
Make Library folder and scaffold core functions 

### ISSUE THREAD

**Issue by alexander-morris** [open-koi/koi-protocol#1]
Add a library folder with the following methods

1. Write to Arweave               X  
2. Fetch Amplify Gateways  ?  
3. Compare Traffic Logs       ??  
4. Verify Proof of work          ???  
5. Prepare vote and sign      ?

Be sure to add a test.js file in the root of the folder

Typescript is a must

**Comment by Sebhatu** [comment]
done
