### ISSUE TITLE
Scaffold core contract buildable 

### ISSUE THREAD

**Issue by alexander-morris** [open-koi/koi-protocol#2]
Contract  
1. Track gateways        
       support registration        
        track state.gateways list  
2. Track KOI Balances 
       staking        
       1000 daily payout
  3. Track Traffic
          verified traffic        ?
          daily payout history ? 
          
   4. Track Registered Content        
          content IDs and owner pub keys
           support transfers        
           
    5. Update KOI contract state

**Comment by Sebhatu** [comment]
implemented,
